/* tslint:disable */
/* eslint-disable */
/**
 * MMS-Team-7
 *  Mentors Management system is a people management app that enables proper. coordination of mentors needed to execute projects, ranging from recruitment to off-boarding. Ensue to go through the app doc below to read more and follow all the instructions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ChangePasswordRequest
 */
export interface ChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordRequest
     */
    'current_password'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordRequest
     */
    'new_password'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordRequest
     */
    'confirm_new_password'?: string;
}
/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'owner_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    'profile_image_url'?: string;
}
/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'website'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'city'?: string;
}
/**
 * 
 * @export
 * @interface CreateFAQResponse
 */
export interface CreateFAQResponse {
    /**
     * 
     * @type {CreateFAQResponseData}
     * @memberof CreateFAQResponse
     */
    'data'?: CreateFAQResponseData;
}
/**
 * 
 * @export
 * @interface CreateFAQResponseData
 */
export interface CreateFAQResponseData {
    /**
     * 
     * @type {string}
     * @memberof CreateFAQResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFAQResponseData
     */
    'question'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFAQResponseData
     */
    'answer'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFAQResponseData
     */
    'category'?: string;
}
/**
 * 
 * @export
 * @interface Discussion
 */
export interface Discussion {
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    'created_at'?: string;
    /**
     * 
     * @type {DiscussionCreatorDetails}
     * @memberof Discussion
     */
    'creator_details'?: DiscussionCreatorDetails;
    /**
     * 
     * @type {Array<Comment>}
     * @memberof Discussion
     */
    'comments'?: Array<Comment>;
}
/**
 * 
 * @export
 * @interface DiscussionCreatorDetails
 */
export interface DiscussionCreatorDetails {
    /**
     * 
     * @type {string}
     * @memberof DiscussionCreatorDetails
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DiscussionCreatorDetails
     */
    'profile_image_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof DiscussionCreatorDetails
     */
    'full_name'?: string;
}
/**
 * 
 * @export
 * @interface DiscussionsIdAddCommentPostRequest
 */
export interface DiscussionsIdAddCommentPostRequest {
    /**
     * 
     * @type {string}
     * @memberof DiscussionsIdAddCommentPostRequest
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DiscussionsIdAddCommentPostRequest
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DiscussionsIdAddCommentPostRequest
     */
    'content'?: string;
}
/**
 * 
 * @export
 * @interface DiscussionsPostRequest
 */
export interface DiscussionsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof DiscussionsPostRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof DiscussionsPostRequest
     */
    'content'?: string;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface FAQ
 */
export interface FAQ {
    /**
     * 
     * @type {string}
     * @memberof FAQ
     */
    'question'?: string;
    /**
     * 
     * @type {string}
     * @memberof FAQ
     */
    'answer'?: string;
    /**
     * 
     * @type {string}
     * @memberof FAQ
     */
    'category'?: string;
}
/**
 * 
 * @export
 * @interface ForgotPasswordPostRequest
 */
export interface ForgotPasswordPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordPostRequest
     */
    'email'?: string;
}
/**
 * 
 * @export
 * @interface GetFAQsResponse
 */
export interface GetFAQsResponse {
    /**
     * 
     * @type {Array<FAQ>}
     * @memberof GetFAQsResponse
     */
    'data'?: Array<FAQ>;
}
/**
 * 
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginRequest
     */
    'password'?: string;
}
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {LoginResponseData}
     * @memberof LoginResponse
     */
    'data'?: LoginResponseData;
}
/**
 * 
 * @export
 * @interface LoginResponseData
 */
export interface LoginResponseData {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseData
     */
    'token'?: string;
    /**
     * 
     * @type {LoginResponseDataPayload}
     * @memberof LoginResponseData
     */
    'payload'?: LoginResponseDataPayload;
    /**
     * 
     * @type {User}
     * @memberof LoginResponseData
     */
    'user'?: User;
}
/**
 * 
 * @export
 * @interface LoginResponseDataPayload
 */
export interface LoginResponseDataPayload {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDataPayload
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDataPayload
     */
    'user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDataPayload
     */
    'user_role'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDataPayload
     */
    'issued_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDataPayload
     */
    'expired_at'?: string;
}
/**
 * 
 * @export
 * @interface ResetPasswordPatchRequest
 */
export interface ResetPasswordPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordPatchRequest
     */
    'new_password'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordPatchRequest
     */
    'confirm_new_password'?: string;
}
/**
 * 
 * @export
 * @interface Socials
 */
export interface Socials {
    /**
     * 
     * @type {SocialsGithubUrl}
     * @memberof Socials
     */
    'github_url'?: SocialsGithubUrl;
    /**
     * 
     * @type {SocialsGithubUrl}
     * @memberof Socials
     */
    'linkedin_url'?: SocialsGithubUrl;
    /**
     * 
     * @type {SocialsGithubUrl}
     * @memberof Socials
     */
    'twitter_url'?: SocialsGithubUrl;
    /**
     * 
     * @type {SocialsGithubUrl}
     * @memberof Socials
     */
    'instagram_url'?: SocialsGithubUrl;
}
/**
 * 
 * @export
 * @interface SocialsGithubUrl
 */
export interface SocialsGithubUrl {
    /**
     * 
     * @type {string}
     * @memberof SocialsGithubUrl
     */
    'value'?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialsGithubUrl
     */
    'is_visible'?: string;
}
/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'details'?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'created_at'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Task
     */
    'mentors'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Task
     */
    'mentor_managers'?: Array<string>;
}
/**
 * 
 * @export
 * @interface TasksPostRequest
 */
export interface TasksPostRequest {
    /**
     * 
     * @type {string}
     * @memberof TasksPostRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof TasksPostRequest
     */
    'details'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TasksPostRequest
     */
    'mentors'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TasksPostRequest
     */
    'mentor_managers'?: Array<string>;
}
/**
 * 
 * @export
 * @interface UpdateUserResquest
 */
export interface UpdateUserResquest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'about'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'website'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'profile_image_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'github_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'linkedin_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'twitter_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResquest
     */
    'instagram_url'?: string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'role'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'about'?: string;
    /**
     * 
     * @type {Contact}
     * @memberof User
     */
    'contact'?: Contact;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'profile_image_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'password_changed_at'?: string;
    /**
     * 
     * @type {Socials}
     * @memberof User
     */
    'socials'?: Socials;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'is_email_verified'?: boolean;
}
/**
 * 
 * @export
 * @interface UsersIdChangePasswordPatch200Response
 */
export interface UsersIdChangePasswordPatch200Response {
    /**
     * 
     * @type {string}
     * @memberof UsersIdChangePasswordPatch200Response
     */
    'result'?: string;
}
/**
 * 
 * @export
 * @interface UsersIdPatch200Response
 */
export interface UsersIdPatch200Response {
    /**
     * 
     * @type {UsersIdPatch200ResponseData}
     * @memberof UsersIdPatch200Response
     */
    'data'?: UsersIdPatch200ResponseData;
}
/**
 * 
 * @export
 * @interface UsersIdPatch200ResponseData
 */
export interface UsersIdPatch200ResponseData {
    /**
     * 
     * @type {User}
     * @memberof UsersIdPatch200ResponseData
     */
    'user'?: User;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Google sign-in callback
         * @param {any} code The authorization code returned by Google after the user approves access
         * @param {any} state A value passed by the client which is returned unchanged in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleCallbackGet: async (code: any, state: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('authGoogleCallbackGet', 'code', code)
            // verify required parameter 'state' is not null or undefined
            assertParamExists('authGoogleCallbackGet', 'state', state)
            const localVarPath = `/auth/google/callback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Initiate Google Sign-In flow by redirecting the user to Google authorization endpoint
         * @summary Initiate Google Sign-In
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleLoginGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/google/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Login a user
         * @param {LoginRequest} credentials Email address and password of the user to authenticate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (credentials: LoginRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentials' is not null or undefined
            assertParamExists('authLoginPost', 'credentials', credentials)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(credentials, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all discussions for a user
         * @param {number} pageId What page to start from
         * @param {number} pageSize What page size to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsGet: async (pageId: number, pageSize: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageId' is not null or undefined
            assertParamExists('discussionsGet', 'pageId', pageId)
            // verify required parameter 'pageSize' is not null or undefined
            assertParamExists('discussionsGet', 'pageSize', pageSize)
            const localVarPath = `/discussions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageId !== undefined) {
                localVarQueryParameter['page_id'] = pageId;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add a comment on discussion
         * @param {DiscussionsIdAddCommentPostRequest} comment Content of the comment and owner\&#39;s full name 
         * @param {string} id Discussion ID to add comment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsIdAddCommentPost: async (comment: DiscussionsIdAddCommentPostRequest, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'comment' is not null or undefined
            assertParamExists('discussionsIdAddCommentPost', 'comment', comment)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('discussionsIdAddCommentPost', 'id', id)
            const localVarPath = `/discussions/{id}/add_comment`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(comment, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a discussion
         * @param {string} id Discussion ID to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('discussionsIdGet', 'id', id)
            const localVarPath = `/discussions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a discussion
         * @param {DiscussionsPostRequest} titleAndContent The discussion new title and content
         * @param {string} id Discussion ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsIdPatch: async (titleAndContent: DiscussionsPostRequest, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'titleAndContent' is not null or undefined
            assertParamExists('discussionsIdPatch', 'titleAndContent', titleAndContent)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('discussionsIdPatch', 'id', id)
            const localVarPath = `/discussions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(titleAndContent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a discussion forum
         * @param {DiscussionsPostRequest} titleAndContent Title and content of the discussion
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsPost: async (titleAndContent: DiscussionsPostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'titleAndContent' is not null or undefined
            assertParamExists('discussionsPost', 'titleAndContent', titleAndContent)
            const localVarPath = `/discussions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(titleAndContent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all FAQs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        faqsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/faqs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create FAQ
         * @param {FAQ} fAQ Details of FAQ to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        faqsPost: async (fAQ: FAQ, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fAQ' is not null or undefined
            assertParamExists('faqsPost', 'fAQ', fAQ)
            const localVarPath = `/faqs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fAQ, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Request for password reset
         * @param {ForgotPasswordPostRequest} email User\&#39;s email to send reset password email/token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPasswordPost: async (email: ForgotPasswordPostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('forgotPasswordPost', 'email', email)
            const localVarPath = `/forgot_password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(email, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all mentor managers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mentorMangersGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mentor_mangers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all mentors 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mentorsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mentors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reset user\'s password
         * @param {ResetPasswordPatchRequest} newPasswordCredentials Current password and new password of the user to update
         * @param {any} resetToken Signed token to reset password
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPasswordPatch: async (newPasswordCredentials: ResetPasswordPatchRequest, resetToken: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newPasswordCredentials' is not null or undefined
            assertParamExists('resetPasswordPatch', 'newPasswordCredentials', newPasswordCredentials)
            // verify required parameter 'resetToken' is not null or undefined
            assertParamExists('resetPasswordPatch', 'resetToken', resetToken)
            const localVarPath = `/reset_password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (resetToken !== undefined) {
                localVarQueryParameter['reset_token'] = resetToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newPasswordCredentials, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all tasks for a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a task
         * @param {string} id Task ID to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('tasksIdGet', 'id', id)
            const localVarPath = `/tasks/:id`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a task
         * @param {TasksPostRequest} titleAndContent The task new title and content
         * @param {string} id Task ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksIdPatch: async (titleAndContent: TasksPostRequest, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'titleAndContent' is not null or undefined
            assertParamExists('tasksIdPatch', 'titleAndContent', titleAndContent)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('tasksIdPatch', 'id', id)
            const localVarPath = `/tasks/:id`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(titleAndContent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a task
         * @param {TasksPostRequest} titleAndContent Title and content of the task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksPost: async (titleAndContent: TasksPostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'titleAndContent' is not null or undefined
            assertParamExists('tasksPost', 'titleAndContent', titleAndContent)
            const localVarPath = `/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(titleAndContent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Changer user\'s password
         * @param {ChangePasswordRequest} passwords Current password and new password of the user to update
         * @param {string} id ID of the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdChangePasswordPatch: async (passwords: ChangePasswordRequest, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'passwords' is not null or undefined
            assertParamExists('usersIdChangePasswordPatch', 'passwords', passwords)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdChangePasswordPatch', 'id', id)
            const localVarPath = `/users/{id}/change_password`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passwords, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update user\'s profile info
         * @param {UpdateUserResquest} usersInfo Update user\&#39;s profile data
         * @param {any} id User\&#39;s ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdPatch: async (usersInfo: UpdateUserResquest, id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'usersInfo' is not null or undefined
            assertParamExists('usersIdPatch', 'usersInfo', usersInfo)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdPatch', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Google sign-in callback
         * @param {any} code The authorization code returned by Google after the user approves access
         * @param {any} state A value passed by the client which is returned unchanged in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authGoogleCallbackGet(code: any, state: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authGoogleCallbackGet(code, state, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Initiate Google Sign-In flow by redirecting the user to Google authorization endpoint
         * @summary Initiate Google Sign-In
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authGoogleLoginGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authGoogleLoginGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Login a user
         * @param {LoginRequest} credentials Email address and password of the user to authenticate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(credentials: LoginRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(credentials, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersIdChangePasswordPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutPost(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List all discussions for a user
         * @param {number} pageId What page to start from
         * @param {number} pageSize What page size to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discussionsGet(pageId: number, pageSize: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Discussion>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discussionsGet(pageId, pageSize, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Add a comment on discussion
         * @param {DiscussionsIdAddCommentPostRequest} comment Content of the comment and owner\&#39;s full name 
         * @param {string} id Discussion ID to add comment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discussionsIdAddCommentPost(comment: DiscussionsIdAddCommentPostRequest, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Comment>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discussionsIdAddCommentPost(comment, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get a discussion
         * @param {string} id Discussion ID to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discussionsIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Discussion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discussionsIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update a discussion
         * @param {DiscussionsPostRequest} titleAndContent The discussion new title and content
         * @param {string} id Discussion ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discussionsIdPatch(titleAndContent: DiscussionsPostRequest, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Discussion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discussionsIdPatch(titleAndContent, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create a discussion forum
         * @param {DiscussionsPostRequest} titleAndContent Title and content of the discussion
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discussionsPost(titleAndContent: DiscussionsPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Discussion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discussionsPost(titleAndContent, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get all FAQs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async faqsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFAQsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.faqsGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create FAQ
         * @param {FAQ} fAQ Details of FAQ to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async faqsPost(fAQ: FAQ, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateFAQResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.faqsPost(fAQ, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Request for password reset
         * @param {ForgotPasswordPostRequest} email User\&#39;s email to send reset password email/token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forgotPasswordPost(email: ForgotPasswordPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersIdChangePasswordPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.forgotPasswordPost(email, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List all mentor managers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mentorMangersGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mentorMangersGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List all mentors 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mentorsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mentorsGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Reset user\'s password
         * @param {ResetPasswordPatchRequest} newPasswordCredentials Current password and new password of the user to update
         * @param {any} resetToken Signed token to reset password
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetPasswordPatch(newPasswordCredentials: ResetPasswordPatchRequest, resetToken: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersIdChangePasswordPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetPasswordPatch(newPasswordCredentials, resetToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List all tasks for a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tasksGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Task>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tasksGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get a task
         * @param {string} id Task ID to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tasksIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tasksIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update a task
         * @param {TasksPostRequest} titleAndContent The task new title and content
         * @param {string} id Task ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tasksIdPatch(titleAndContent: TasksPostRequest, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tasksIdPatch(titleAndContent, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create a task
         * @param {TasksPostRequest} titleAndContent Title and content of the task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tasksPost(titleAndContent: TasksPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tasksPost(titleAndContent, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Changer user\'s password
         * @param {ChangePasswordRequest} passwords Current password and new password of the user to update
         * @param {string} id ID of the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdChangePasswordPatch(passwords: ChangePasswordRequest, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersIdChangePasswordPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdChangePasswordPatch(passwords, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update user\'s profile info
         * @param {UpdateUserResquest} usersInfo Update user\&#39;s profile data
         * @param {any} id User\&#39;s ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdPatch(usersInfo: UpdateUserResquest, id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersIdPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdPatch(usersInfo, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Google sign-in callback
         * @param {any} code The authorization code returned by Google after the user approves access
         * @param {any} state A value passed by the client which is returned unchanged in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleCallbackGet(code: any, state: any, options?: any): AxiosPromise<LoginResponse> {
            return localVarFp.authGoogleCallbackGet(code, state, options).then((request) => request(axios, basePath));
        },
        /**
         * Initiate Google Sign-In flow by redirecting the user to Google authorization endpoint
         * @summary Initiate Google Sign-In
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleLoginGet(options?: any): AxiosPromise<void> {
            return localVarFp.authGoogleLoginGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Login a user
         * @param {LoginRequest} credentials Email address and password of the user to authenticate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(credentials: LoginRequest, options?: any): AxiosPromise<LoginResponse> {
            return localVarFp.authLoginPost(credentials, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost(options?: any): AxiosPromise<UsersIdChangePasswordPatch200Response> {
            return localVarFp.authLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all discussions for a user
         * @param {number} pageId What page to start from
         * @param {number} pageSize What page size to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsGet(pageId: number, pageSize: number, options?: any): AxiosPromise<Array<Discussion>> {
            return localVarFp.discussionsGet(pageId, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add a comment on discussion
         * @param {DiscussionsIdAddCommentPostRequest} comment Content of the comment and owner\&#39;s full name 
         * @param {string} id Discussion ID to add comment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsIdAddCommentPost(comment: DiscussionsIdAddCommentPostRequest, id: string, options?: any): AxiosPromise<Array<Comment>> {
            return localVarFp.discussionsIdAddCommentPost(comment, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a discussion
         * @param {string} id Discussion ID to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsIdGet(id: string, options?: any): AxiosPromise<Discussion> {
            return localVarFp.discussionsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a discussion
         * @param {DiscussionsPostRequest} titleAndContent The discussion new title and content
         * @param {string} id Discussion ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsIdPatch(titleAndContent: DiscussionsPostRequest, id: string, options?: any): AxiosPromise<Discussion> {
            return localVarFp.discussionsIdPatch(titleAndContent, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a discussion forum
         * @param {DiscussionsPostRequest} titleAndContent Title and content of the discussion
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discussionsPost(titleAndContent: DiscussionsPostRequest, options?: any): AxiosPromise<Discussion> {
            return localVarFp.discussionsPost(titleAndContent, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all FAQs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        faqsGet(options?: any): AxiosPromise<GetFAQsResponse> {
            return localVarFp.faqsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create FAQ
         * @param {FAQ} fAQ Details of FAQ to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        faqsPost(fAQ: FAQ, options?: any): AxiosPromise<CreateFAQResponse> {
            return localVarFp.faqsPost(fAQ, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Request for password reset
         * @param {ForgotPasswordPostRequest} email User\&#39;s email to send reset password email/token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPasswordPost(email: ForgotPasswordPostRequest, options?: any): AxiosPromise<UsersIdChangePasswordPatch200Response> {
            return localVarFp.forgotPasswordPost(email, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all mentor managers 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mentorMangersGet(options?: any): AxiosPromise<Array<User>> {
            return localVarFp.mentorMangersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all mentors 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mentorsGet(options?: any): AxiosPromise<Array<User>> {
            return localVarFp.mentorsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reset user\'s password
         * @param {ResetPasswordPatchRequest} newPasswordCredentials Current password and new password of the user to update
         * @param {any} resetToken Signed token to reset password
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPasswordPatch(newPasswordCredentials: ResetPasswordPatchRequest, resetToken: any, options?: any): AxiosPromise<UsersIdChangePasswordPatch200Response> {
            return localVarFp.resetPasswordPatch(newPasswordCredentials, resetToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all tasks for a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksGet(options?: any): AxiosPromise<Array<Task>> {
            return localVarFp.tasksGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a task
         * @param {string} id Task ID to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksIdGet(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.tasksIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a task
         * @param {TasksPostRequest} titleAndContent The task new title and content
         * @param {string} id Task ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksIdPatch(titleAndContent: TasksPostRequest, id: string, options?: any): AxiosPromise<Task> {
            return localVarFp.tasksIdPatch(titleAndContent, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a task
         * @param {TasksPostRequest} titleAndContent Title and content of the task
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksPost(titleAndContent: TasksPostRequest, options?: any): AxiosPromise<Task> {
            return localVarFp.tasksPost(titleAndContent, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Changer user\'s password
         * @param {ChangePasswordRequest} passwords Current password and new password of the user to update
         * @param {string} id ID of the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdChangePasswordPatch(passwords: ChangePasswordRequest, id: string, options?: any): AxiosPromise<UsersIdChangePasswordPatch200Response> {
            return localVarFp.usersIdChangePasswordPatch(passwords, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update user\'s profile info
         * @param {UpdateUserResquest} usersInfo Update user\&#39;s profile data
         * @param {any} id User\&#39;s ID to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdPatch(usersInfo: UpdateUserResquest, id: any, options?: any): AxiosPromise<UsersIdPatch200Response> {
            return localVarFp.usersIdPatch(usersInfo, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Google sign-in callback
     * @param {any} code The authorization code returned by Google after the user approves access
     * @param {any} state A value passed by the client which is returned unchanged in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authGoogleCallbackGet(code: any, state: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authGoogleCallbackGet(code, state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Initiate Google Sign-In flow by redirecting the user to Google authorization endpoint
     * @summary Initiate Google Sign-In
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authGoogleLoginGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authGoogleLoginGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Login a user
     * @param {LoginRequest} credentials Email address and password of the user to authenticate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authLoginPost(credentials: LoginRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authLoginPost(credentials, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authLogoutPost(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all discussions for a user
     * @param {number} pageId What page to start from
     * @param {number} pageSize What page size to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public discussionsGet(pageId: number, pageSize: number, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).discussionsGet(pageId, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add a comment on discussion
     * @param {DiscussionsIdAddCommentPostRequest} comment Content of the comment and owner\&#39;s full name 
     * @param {string} id Discussion ID to add comment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public discussionsIdAddCommentPost(comment: DiscussionsIdAddCommentPostRequest, id: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).discussionsIdAddCommentPost(comment, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a discussion
     * @param {string} id Discussion ID to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public discussionsIdGet(id: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).discussionsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a discussion
     * @param {DiscussionsPostRequest} titleAndContent The discussion new title and content
     * @param {string} id Discussion ID to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public discussionsIdPatch(titleAndContent: DiscussionsPostRequest, id: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).discussionsIdPatch(titleAndContent, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a discussion forum
     * @param {DiscussionsPostRequest} titleAndContent Title and content of the discussion
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public discussionsPost(titleAndContent: DiscussionsPostRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).discussionsPost(titleAndContent, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all FAQs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public faqsGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).faqsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create FAQ
     * @param {FAQ} fAQ Details of FAQ to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public faqsPost(fAQ: FAQ, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).faqsPost(fAQ, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Request for password reset
     * @param {ForgotPasswordPostRequest} email User\&#39;s email to send reset password email/token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public forgotPasswordPost(email: ForgotPasswordPostRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).forgotPasswordPost(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all mentor managers 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public mentorMangersGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).mentorMangersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all mentors 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public mentorsGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).mentorsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reset user\'s password
     * @param {ResetPasswordPatchRequest} newPasswordCredentials Current password and new password of the user to update
     * @param {any} resetToken Signed token to reset password
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public resetPasswordPatch(newPasswordCredentials: ResetPasswordPatchRequest, resetToken: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).resetPasswordPatch(newPasswordCredentials, resetToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all tasks for a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tasksGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).tasksGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a task
     * @param {string} id Task ID to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tasksIdGet(id: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).tasksIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a task
     * @param {TasksPostRequest} titleAndContent The task new title and content
     * @param {string} id Task ID to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tasksIdPatch(titleAndContent: TasksPostRequest, id: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).tasksIdPatch(titleAndContent, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a task
     * @param {TasksPostRequest} titleAndContent Title and content of the task
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tasksPost(titleAndContent: TasksPostRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).tasksPost(titleAndContent, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Changer user\'s password
     * @param {ChangePasswordRequest} passwords Current password and new password of the user to update
     * @param {string} id ID of the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public usersIdChangePasswordPatch(passwords: ChangePasswordRequest, id: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersIdChangePasswordPatch(passwords, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update user\'s profile info
     * @param {UpdateUserResquest} usersInfo Update user\&#39;s profile data
     * @param {any} id User\&#39;s ID to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public usersIdPatch(usersInfo: UpdateUserResquest, id: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersIdPatch(usersInfo, id, options).then((request) => request(this.axios, this.basePath));
    }
}


